"""Changed column model in table cars

Revision ID: 34421ff3d62e
Revises: 6593b289b055
Create Date: 2022-03-30 14:12:08.169676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34421ff3d62e'
down_revision = '6593b289b055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
